### ISSUE TITLE
incompatibility with tweetnacl in some environments (TypeError: unexpected type, use Uint8Array)

### ISSUE THREAD

**Issue by prestwich** [nearprotocol/nearlib#226]
`tweetnacl` is used for keys. It checks that arguments are `instanceof Uint8Array`.
https://github.com/dchest/tweetnacl-js/blob/af1919cba27fb9a98c9fba659e675cde6e8b36e6/nacl-fast.js#L2317-L2324

The nearlib serializer returns `Buffer`s. In some environments (e.g. jest) this will fail the type check in `tweetnacl`

this will cause tests to break even when code will work in production

**Comment by prestwich** [comment]
side note: this is fixed in `jest@25.1.0` so it may be a version-specific jest bug

**Comment by vgrichina** [comment]
I've seen this problem as well with Jest's fake browser environment. At the moment my workaround was just using Node.js environment instead – there is also more complicated workaround with creating custom Jest environment which would properly plumb Buffer/Uint8Array stuff.

Cool to know that it's fixed in latest `jest`.

**Comment by prestwich** [comment]
```
    TypeError: unexpected type, use Uint8Array
      at checkArrayTypes (node_modules/nearlib/node_modules/tweetnacl/nacl-fast.js:2165:13)
      at Function.Object.<anonymous>.nacl.sign.keyPair.fromSecretKey (node_modules/nearlib/node_modules/tweetnacl/nacl-fast.js:2318:3)
      at new KeyPairEd25519 (node_modules/nearlib/lib/utils/key_pair.js:89:58)
      at Function.fromString (node_modules/nearlib/lib/utils/key_pair.js:67:40)
      at new NearProvider (src/index.js:23:47)
      at withWeb3 (test/near_provider.test.js:7:21)
      at Suite.describe.only (test/near_provider.test.js:71:34)
      at Suite.Object.<anonymous>.describe (test/near_provider.test.js:70:14)
      at Object.<anonymous> (test/near_provider.test.js:34:1)
```

**Comment by vgrichina** [comment]
Related stuff:
https://gitmemory.com/issue/facebook/jest/2549/521172632

Closing this for now, hopefully should be Googleable.
